// src/agents/remediationAgent.js
const callOllama = require("../config/callOllama");

const remediationAgent = async (rootCauseResult) => {
  try {
    const finding = validatedResult?.finding || "Unknown finding";
    const validation = validatedResult?.validation || {};
    const rootCause = rootCauseResult?.root_cause || {};
    const prompt = `
          You are a senior cybersecurity remediation engineer working within an automated
          multi-agent security pipeline.

          You are provided with the FULL security analysis object generated by previous agents,
          including validation and root cause analysis.

          Your responsibility is to define precise remediation actions that directly eliminate
          the identified root cause and prevent recurrence.

          --------------------------------------------------
          REMEDIATION GUIDELINES
          --------------------------------------------------

          1. Root-cause alignment
            - Every remediation step MUST directly address the identified root cause
            - Do NOT introduce generic or unrelated security advice

          2. Practicality
            - Steps must be safe for production environments
            - Prefer minimal, targeted changes over large refactors
            - Assume developers and system administrators will apply these steps

          3. Scope discipline
            - Do NOT explain exploitation techniques
            - Do NOT restate the finding unless required for clarity
            - Do NOT modify or reinterpret existing analysis fields

          4. Applicability rules
            - If code-level changes are not applicable, explicitly state so
            - If infrastructure or configuration is involved, be explicit and precise
            - Avoid naming compliance standards unless unavoidable

          --------------------------------------------------
          INPUT OBJECT (FROM PREVIOUS AGENT)
          --------------------------------------------------
          FINDING:
          ${JSON.stringify(finding, null, 2)}

          VALIDATION:
          ${JSON.stringify(validation, null, 2)}

          ROOTCAUSE:
          ${JSON.stringify(rootCause, null, 2)}

          --------------------------------------------------
          OUTPUT REQUIREMENTS
          --------------------------------------------------
          - Output ONLY valid JSON
          - No markdown
          - No explanations outside JSON
          - Clear, actionable, implementation-ready language

          --------------------------------------------------
          OUTPUT SCHEMA (STRICT)
          --------------------------------------------------
          {
            "fix_strategy": "<1–2 sentence summary describing how the remediation removes the root cause>",
            "immediate_actions": [
              "<Ordered remediation step 1>",
              "<Ordered remediation step 2>"
            ],
            "code_level_changes": "<Description of required code changes or 'Not applicable'>",
            "configuration_or_system_changes": "<Configuration or system-level remediation or 'Not applicable'>",
            "preventive_controls": [
              "<Control that prevents recurrence>",
              "<Optional additional control>"
            ],
            "verification_steps": [
              "<How to confirm the fix is effective>",
              "<Optional additional verification>"
            ]
          }
          `;

    const raw = await callOllama(prompt);

    const remediation = JSON.parse(raw.match(/\{[\s\S]*\}/)[0]);

    // 🔥 Chain-safe enrichment
    return {
      ...rootCauseResult,
      remediation,
    };
  } catch (error) {
    console.error("Remediation Agent Error:", error.message);

    return {
      ...rootCauseResult,
      remediation: {
        fix_strategy:
          "Remediation could not be generated due to insufficient or malformed analysis output.",
        immediate_actions: [],
        code_level_changes: "Not applicable",
        configuration_or_system_changes: "Not applicable",
        preventive_controls: [],
        verification_steps: [],
      },
    };
  }
};

export default remediationAgent;
