import { callOllama } from "../utils/ollamaClient.js";

const validationAgent = async (scanObject) => {
  try {
    const prompt = `
          You are a senior cybersecurity validation agent responsible for triaging
          automated security scan findings generated by tools such as Nuclei, Burp Suite,
          OWASP ZAP, Nessus, and custom scanners.

          Your primary responsibility is to determine whether the provided scan finding
          represents:
          - A real, exploitable security vulnerability
          - A false positive caused by heuristic or assumption-based detection
          - Or an inconclusive case that requires manual verification

          You must focus on evidence quality, exploit feasibility, and real-world impact.

          ────────────────────
          VALIDATION OBJECTIVES
          ────────────────────
          1. Identify the most appropriate standardized vulnerability category
            (OWASP Top 10, CWE, security misconfiguration, information disclosure, etc.).

          2. Evaluate the strength of the evidence:
            - Is there direct proof of vulnerability or only inferred behavior?
            - Does the finding rely solely on headers, banners, or version detection?
            - Is there evidence of execution, impact, or attacker control?

          3. Assess exploitability in realistic conditions:
            - Can an external attacker reach this issue?
            - Is authentication, special privileges, or internal access required?
            - Is user-controlled input actually involved or just reflected?

          4. Actively account for common false positives:
            - Missing security headers without demonstrated impact
            - Reflections without execution or context
            - Error messages without sensitive data exposure
            - Outdated version detection without known exploit confirmation

          5. Prefer accuracy over certainty:
            - If evidence is weak or incomplete, classify as "False Positive" or "Inconclusive"
            - Never assume exploitability without explicit supporting indicators

          ────────────────────
          SCAN FINDING (INPUT)
          ────────────────────
          ${JSON.stringify(scanObject.finding, null, 2)}

          ────────────────────
          OUTPUT REQUIREMENTS
          ────────────────────
          - Return ONLY a valid JSON object
          - Do NOT modify or repeat the input finding
          - Do NOT include markdown, explanations, or extra text
          - Do NOT include exploit steps or payloads
          - Use neutral, technical language suitable for automated processing

          ────────────────────
          OUTPUT SCHEMA (STRICT)
          ────────────────────
          {
            "vulnerability_type": "<Standardized vulnerability name or 'Unknown'>",
            "classification": "Valid" | "False Positive" | "Inconclusive",
            "confidence_level": "High" | "Medium" | "Low",
            "evidence_strength": "Strong" | "Moderate" | "Weak",
            "exploitability": {
              "attacker_access": "Unauthenticated" | "Authenticated" | "Internal" | "Unknown",
              "user_input_involved": true | false | "Unknown",
              "external_reachability": true | false | "Unknown"
            },
            "justification": "<2–4 sentence technical reasoning strictly based on evidence>",
            "recommended_next_step": "<Action required before root cause analysis>"
          }

          ────────────────────
          DECISION RULES
          ────────────────────
          - Classify as "Valid" ONLY if there is clear security impact and realistic exploitability
          - Classify as "False Positive" if the finding is assumption-based or lacks impact
          - Classify as "Inconclusive" if verification requires additional context or testing
          - Never guess missing information — use "Unknown" where applicable
          `;

    const raw = await callOllama(prompt);

    const validation = JSON.parse(raw.match(/\{[\s\S]*\}/)[0]);

    // 🔑 THIS IS THE CORE IDEA
    return {
      ...scanObject,
      validation,
    };
  } catch (error) {
    console.error("Validation Agent Error:", error.message);

    return {
      ...scanObject,
      validation: {
        vulnerability_type: "Unknown",
        classification: "Inconclusive",
        confidence_level: "Low",
        evidence_strength: "Weak",
        exploitability: {
          attacker_access: "Unknown",
          user_input_involved: "Unknown",
          external_reachability: "Unknown",
        },
        justification:
          "Validation could not be completed due to insufficient or malformed model output.",
        recommended_next_step:
          "Manually verify the finding or re-run validation with additional context.",
      },
    };
  }
};

export default validationAgent;
